source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  end


target 'NativeFlutter' do
  
  #  use_modular_headers!
  use_frameworks!
  
  install_all_flutter_pods(flutter_application_path)
  
  pod 'Moya'
  
  pod 'Then'

  pod 'SnapKit'

  
end
